dist: trusty
sudo: false
language: java

jdk:
  - openjdk8

before_install:
  - git clone https://github.com/fastily/jwiki.git
  - cd jwiki
  - ./gradlew -x test build publishToMavenLocal
  - cd ../

notifications:
  email: false
  